### ISSUE TITLE
Add styling options

### ISSUE THREAD

**Issue by Protoss78** [Granze/flip-clock#9]
It would be great if the flip-clock would be stylable from outside. Especially when you want to use it on a web page that has a dark theme.

Useful style options would be:
- Digit color
- Card background
- Font size

**Comment by Granze** [comment]
This is a nice idea, I'll start working on this soon

**Comment by Granze** [comment]
Release v1.2.6 exposes some custom properties for external styling: https://github.com/Granze/flip-clock/releases/tag/v1.2.6.
Let me know what you think! :)
